feat: add trip preferences to Trips query
AtB-AS/atb-bff pull request #124
Opened 2022-02-10 13:19 UTC by rosvik

BFF-del av AtB-AS/mittatb-app#2019

Legger til 4 optional parameter for Trips-endepunktet 

- transferPenalty
- waitReluctance
- walkReluctance
- walkSpeed

2022-02-11 08:44 UTC, gorandalum approved these changes

2022-02-11 08:46 UTC, gorandalum requested changes
Mangler oppdatering i swagger.

2022-02-11 08:51 UTC, rosvik commented
@gorandalum Sant det! La til nå.

2022-02-14 09:18 UTC, mikaelbr approved these changes
Ser bra ut her. Bakoverkompatibelt og dekket i swagger 👌

2022-02-14 10:00 UTC, merged